### PR TITLE
Adds change notification models to core package

### PR DESCRIPTION
**Pull request by rkodev**
## Overview

Resolves https://github.com/microsoftgraph/msgraph-sdk-go/issues/481

Re-introduces change notification models in the `core` package that were removed as a result of the changes in kiota https://github.com/microsoft/kiota/issues/2543

## Testing
Added unit test to ensure package is not trimmed on the next release

### CODE REVIEW

**Review by baywet — CHANGES_REQUESTED** [review]
For this I believe @andrueastman opted out to have the types in core I believe? (Can you confirm)
If that's not the case @licantrop0 reached out saying they were missing from beta the other day.
We should probably align.

**Comment by andrueastman** [comment]
Just to confirm @baywet 
We went the service library route incase the models ended up differing based on the endpoint. 
https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/1856#issuecomment-1523469523

**Comment by baywet** [comment]
Thanks for the confirmation. What namespace are the beta models under?

**Comment by andrueastman** [comment]
They would fall under the same namespace as the models namespace for beta/v1. 
v1 - `Microsoft.Graph.Models`
beta - `Microsoft.Graph.Beta.Models`

If any of the models get referenced through a future new path and therefore get generated by Kiota, we would simply delete these and default to the generated file without breaking anything.

**Comment by baywet** [comment]
Thanks @andrueastman makes sense. I'm not sure why @licantrop0 was not able to import them for beta then, maybe using an outdated version.

@rkodev the only concern I have at this point is the fact the import path for these models is different from all other models, and if we started having an endpoint referencing them, we'd end up with duplicates. What about moving them to the models directory and updating the pipeline so they don't get deleted?

**Comment by Licantrop0** [comment]
I was not talking about notifications, but `BatchRequestContent`:
image

**Comment by rkodev** [comment]
@baywet Added the models to the same path and exclude in code generation https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/1028

**Review by baywet — APPROVED** [review]
Thanks for making the changes

**Pull request merged**
