### PR TITLE
adds skiptoken parameter support for users

### PR DESCRIPTION
**Pull request by melgendyjc**
## Overview

Skiptoken is needed for user searches

### Demo

Optional. Screenshots, examples, etc.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output

### CODE REVIEW

**Review by baywet — CHANGES_REQUESTED** [review]
Hi @melgendyjc 
Thanks for the contribution!
Unfortunately we cannot merge this pull request. The section of the code that's impacted is actually auto-generated using [kiota](https://github.com/microsoft/kiota) and would get overwritten at the next generation cycle.

Also, you should not need a Skip Token parameter. The only way to get a URI with a skip token is through the service as the next link value. And those next links should be treated as opaque: don't try to parse them.
If you need to store them, store the whole link, not just the token.
If you need to get the next page, you can use [the page iterator](https://docs.microsoft.com/en-us/graph/sdks/paging?tabs=Go) to do that for you automatically.

Let me know if you have any other question/comment.

**Comment by melgendyjc** [comment]
> 

Hi @baywet 
I believe the page iterator is used for a different functionality. I cannot use it to "skip" the search, I have to iterate and that starts the iteration from the beginning each time.
simply adding skiptoken to the search skips to the position. helpful for larger lists.

**Comment by baywet** [comment]
@melgendyjc 
Thanks for the additional information. Is your application displaying a paging UI where people click "next" and it loads more results? (or infinite scroll).
In that case, you can use this constructor instead and pass in the next link from the previous request.
https://github.com/microsoftgraph/msgraph-sdk-go/blob/eb2d097f9010a618832461f649740084d7823b02/users/users_request_builder.go#L72

**Comment by baywet** [comment]
closing due to inactivity

**Comment by dhubertusjc** [comment]
@baywet Thanks for your previous review! QQ I am currently looking into using ```NewUsersRequestBuilder``` and am struggling to figure out its usage. Is there any documentation specific to this usage or code snippets?

For context:
* Client set up like so: https://docs.microsoft.com/en-us/graph/sdks/use-beta?tabs=Go
* I can successfully make ```client.User().GetWithRequestConfigurationAndResponseHandler()```
   * I receive a ```nextLink``` in our response that I would like to use on subsequent requests
* How do I use ```NewUsersRequestBuilder``` in combination with ```client``` and ```nextLink```?

Anything would help thanks!!

**Comment by baywet** [comment]
```golang
//nextlink is the next link from the previous response
//requestAdapter is the request adapter you used to initialize the client
//users is an import of msgraph-sdk-go/users
requestBuilder := users.NewUsersRequestBuilder(nextLink, requestAdapter)
response, err := resquestBuilder.Get()
```

**Comment by dhubertusjc** [comment]
Ah I see thanks!

**Pull request closed without merging**
